### PR TITLE
Split DrawContents into BeginContents and EndContents

### PR DESCRIPTION
**Pull request by leiradel**

### CODE REVIEW

**Comment by ocornut** [comment]
Quick feedback, sorry I didn't answer your earlier question in #23

At this point, I feel all you would need to do is to add a `float OptFooterExtraHeight = 0.0f` in the structure and use that in DrawContents, no need for new functions?

PS: The choice to use SetCursorPosX is awkward in the first place, but it could be done anywhere and I believe would be better expressed as a Dummy() or ItemAdd() call to cover the ASCII area. Either way, it could be done at the first call and doesn't necessitate an extra function.

**Comment by leiradel** [comment]
Ok I'll try that later.

**Comment by leiradel** [comment]
Sending a new PR.

**Comment by ocornut** [comment]
You can force push into same branch to reuse same PR btw :) thanks

**Pull request closed without merging**
