### PR TITLE
Add BgColorFn for byte coloring and InteractFn for interactions on bytes

### PR DESCRIPTION
**Pull request by StrikerX3**
BgColorFn works just like HighlightFn, except it allows coloring all bytes in view instead of just the highlighted bytes. The return value is the color; 0 means don't change the color. HighlightFn takes priority over BgColorFn.

InteractFn can be used to display popups, context menus, etc.

image

image

### CODE REVIEW

**Comment by silverweed** [comment]
Any chance this might be merged?

**Comment by ocornut** [comment]
Thank you. I will work on this now. But for the records, if you add two features please always split them in two commits otherwise it is very likely going to delay their processing.

**Comment by ocornut** [comment]
Merged the BgColorFn part (with a few tweaks/rework to simplify the code).

**Comment by ocornut** [comment]
I am not sure I agree with your design for InteractFn.
Wouldn't it be simpler/nicer to expose e.g. `size_t HoveredAddr` in the memory editor and let user do their thing?
Do you think you could redesign this based on this idea? (after updating to latest I suppose)
Thank you!

**Comment by StrikerX3** [comment]
I have opened a new PR (#47) to redesign InteractFn as suggested. Thank you for the idea!

**Comment by ocornut** [comment]
Thanks, I'll close this PR now. Please confirm that the new interface does the job you need to do in your tool :)

**Pull request closed without merging**
